name: authorization
description: test flutter project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  flutter_bloc: 8.1.3
  flutter_secure_storage: 8.0.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  intl: 0.18.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.2
  json_serializable: 6.7.1
  build_runner: 2.4.6

flutter:

  uses-material-design: true
flutter_intl:
  enabled: true